# Generated by Django 2.1 on 2018-08-12 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='prueba',
            new_name='p',
        ),
    ]
