# Generated by Django 2.1 on 2018-08-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='direccion_correo',
            field=models.CharField(default='No ha introducido una dirección de correo', max_length=100),
        ),
    ]
