# Generated by Django 2.1 on 2018-08-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_comentario_direccion_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='nombre',
            field=models.CharField(default='No ha introducido un nombre', max_length=100),
        ),
    ]
