# Generated by Django 2.1 on 2018-09-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_comentario_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universidad', models.CharField(default='No ha introducido una universidad', max_length=100)),
                ('grado', models.CharField(default='No ha introducido un grado', max_length=100)),
                ('pregunta', models.TextField(default='No ha introducido un comentario')),
                ('detalles', models.TextField(default='No ha introducido detalles')),
                ('email', models.CharField(default='No ha introducido email', max_length=100)),
            ],
        ),
    ]
