# Generated by Django 2.1 on 2018-10-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_pregunta'),
    ]

    operations = [
        migrations.CreateModel(
            name='falta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('falta', models.TextField(default='No ha introducido nada que falte')),
            ],
        ),
    ]
