# Generated by Django 2.1 on 2018-10-28 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_falta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='falta',
            old_name='falta',
            new_name='texto_falta',
        ),
    ]
