# Generated by Django 2.1 on 2018-12-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_auto_20181028_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='No ha introducido', max_length=100)),
                ('contraseña', models.CharField(default='No ha introducido', max_length=100)),
                ('email', models.CharField(default='No ha introducido', max_length=100)),
                ('credenciales', models.TextField(default='No ha introducido nada')),
            ],
        ),
    ]
