# Generated by Django 2.1 on 2018-12-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(default='No ha introducido', max_length=100, primary_key=True, serialize=False),
        ),
    ]
