# Generated by Django 2.1 on 2019-01-05 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_auto_20181215_1749'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usuario',
        ),
    ]
